### PR TITLE
Enable CI build

### PR DESCRIPTION
**Pull request by drfiemost**
CI build for Linux (Ubuntu) and MacOS

### CODE REVIEW

**Comment by Wohlstand** [comment]
What if make a separated files for each OS? That's should be easier to maintain both of them. I going to add other OSes and build configs too.

**Comment by drfiemost** [comment]
Dunno, strategies are made exactly to make it more manageable and allow adding more configurations.
If you prefer however it can be easily split into multiple files.

**Comment by Wohlstand** [comment]
I prefer separated files to don't mix up different operating systems flows, but at the same file I can easily have a whole matrix of different builds even including different Ubuntu versions or something also (you may see that at my TheXTech project).

**Comment by drfiemost** [comment]
Splitted into Linux and MacOS files

**Comment by drfiemost** [comment]
Also added a Windows Visual Studio build

**Comment by Wohlstand** [comment]
Looks better. There is MinGW Windows build is still needed too. Also, better to download SDL package from GitHub releases, not from libsdl-org, that just overloads their server. I.e. download from here, for example: https://github.com/libsdl-org/SDL/releases/tag/release-2.28.4

**Comment by drfiemost** [comment]
Done and done.

**Comment by Wohlstand** [comment]
Looks much better now!
I'll merge this, and if something doesn't work properly, I'll try to fix by myself then.

**Pull request merged**
