### PR TITLE
bump minimum required cmake version to 3.12 because of string(JOIN ..)

### PR DESCRIPTION
**Pull request by sezero**

### CODE REVIEW

**Comment by sezero** [comment]
Your choice.

**Comment by sezero** [comment]
P.S.: I won't be doing that, it's up to you to cook a compatible thing :)

**Comment by Wohlstand** [comment]
Just now I made a change that replaces JOIN with a foreach. I also verified the work on CMake 3.3, and it just works.

P.S. I think, I'll add the CMake 3.3 CI to verify the compatibiltiy for next times.

**Comment by sezero** [comment]
> Just now I made a change that replaces JOIN with a foreach. I also verified the work on CMake 3.3, and it just works.

Yes: tested, and indeed it works

> P.S. I think, I'll add the CMake 3.3 CI to verify the compatibiltiy for next times.

I like seeing conservative guys (in terms of old-versioned tools and software) :))

If only this project hadn't used c++11, and even better if it were written in C :))

**Comment by Wohlstand** [comment]
C++11 is old enough, and almost every compiler supports it (Except of OpenWatcom that supports it badly, even C++98 has some troubles too). Anyway, the compiler support matters on which platforms and toolkits were wanted to be used. Speaking about compilers, DJGPP allows to use modern C++ and target to DOS platform to work on 386 compulters (the DOS player with my libADLMIDI works on i486DX2 on DOS 6.22 just fine). When developing a library, it's always better to support a wider set of toolchains including old one.

**Pull request closed without merging**
